// <auto-generated />
using System;
using Baum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baum.AvaloniaApp.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Baum.AvaloniaApp.Services.Database.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoundChange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Baum.AvaloniaApp.Services.Database.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AncestorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AncestorId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Baum.AvaloniaApp.Services.Database.Language", b =>
                {
                    b.HasOne("Baum.AvaloniaApp.Services.Database.Language", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Baum.AvaloniaApp.Services.Database.Word", b =>
                {
                    b.HasOne("Baum.AvaloniaApp.Services.Database.Word", "Ancestor")
                        .WithMany()
                        .HasForeignKey("AncestorId");

                    b.HasOne("Baum.AvaloniaApp.Services.Database.Language", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Baum.AvaloniaApp.Services.Database.Language", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
